### ISSUE TITLE
Send as JSON

### ISSUE THREAD

**Issue by DamienPV** [yulii/capistrano-hook#9]
Hi !
I have a minor issue working with your gem :
I try to send a webhook to Discord but cannot manage to set header to JSON, is there an easy way I can achieve this ? Right now I'm stuck with` "content-type | application/x-www-form-urlencoded"`
Thank you :)

**Comment by yulii** [comment]
Hi, @DamienPV 
Capistrano-hook version 0.4.0 or later will be set to `application/json` by default.

For an example configuration for discord, please refer to the following link.
https://github.com/yulii/capistrano-hook/blob/ca8b36d4f1abee8d1db01b5d6b80b7e485773081/config/deploy/discord.rb#L26-L31

I didn't notice this issue because I kept using the old Slack API. 😅 
Thank you for your report.

**Comment by ghost** [comment]
Hi @yulii ,
Thank you, for the update and for the documentation 🙌 
Works perfectly 👌
